### ISSUE TITLE
Panel zoom out when using  '@fingers-key' key

### ISSUE THREAD

**Issue by pvskp** [Morantron/tmux-fingers#123]
When in zoomed into a pane, using the <prefix>+F key makes the pane zoom out. Is this expected?

https://github.com/user-attachments/assets/aa2aadee-617b-4e88-89ee-d4d1341cdbf0

**Comment by Morantron** [comment]
hmmm, that shouldn't happen ™️ 

what version of tmux are you using?

**Comment by pvskp** [comment]
The last stable one:

```bash
(base) [~]$ tmux -V
tmux 3.4
```

I thought that could be something with my config, but running it with this minimal config still causes the issue:

```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Morantron/tmux-fingers'

run '~/.tmux/plugins/tpm/tpm'
```

**Comment by pvskp** [comment]
In case it still helps:

```
(base) [main][~/.config/nvim]$ cat /tmp/tmux-$(echo $TMUX | cut -f2 -d',')/tmux-fingers/config.json | jq '.tmux_version'
"3.4"
``

**Comment by Morantron** [comment]
Fixed in 2.2.0

**Comment by augustobmoura** [comment]
I'm still having this problem for some reason, on tmux 3.5a. @Morantron do you know what could be causing it?
I'm using https://github.com/gpakosz/.tmux as well

**Comment by Morantron** [comment]
> I'm still having this problem for some reason, on tmux 3.5a. [@Morantron](https://github.com/Morantron) do you know what could be causing it? I'm using https://github.com/gpakosz/.tmux as well

Cannot reproduce it 🤔 

What's the output of `tmux run "#{@fingers-cli} info"`?

**Comment by augustobmoura** [comment]
> tmux run "#{@fingers-cli} info"

```
+---------------------+-----------------------------------------------------+
| tmux-fingers        | 2.4.1                                               |
| xdg-root-folder     | /home/amoura/.local/state/tmux-fingers/tmux-2139554 |
| log-path            | /home/amoura/.local/state/tmux-fingers/fingers.log  |
| installation-method | download-binary                                     |
| tmux-version        | tmux 3.5a                                           |
| crystal-version     | 1.14.1                                              |
+---------------------+-----------------------------------------------------+
```

Well, I reset my `.tmux.conf.local` to the same as in `oh-my-tmux`, and it seems that the problem is fixed now. I guess some settings were outdated, or something else was breaking it
